package cps2002.game;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

/* this class tests the functionality of the Game class */

public class GameTest {

    private Game g;
    private Map tm;
    private Position pos;
    private Position treasurePos;

    // set up the game, map, and two position instances
    @Before
    public void setup(){
        g = new Game();
        tm = new Map(4);
        pos = new Position(2,2);
        treasurePos = new Position(4,2);
    }



    // test setNumPlayers. Expected true
    @Test
    public void testSetNumOfPlayersWithTrueCondition(){

        boolean ans = g.setNumPlayers(4);

        boolean expected = true;

        assertEquals(expected, ans);
    }

    // test setNumPlayers. Expected false because of too little players
    @Test
    public void testSetNumOfPlayersWithFalseCondition(){

        boolean ans = g.setNumPlayers(-1);
        boolean expected = false;

        assertEquals(expected, ans);
    }

    // test setNumPlayers. Expected false because of too many players
    @Test
    public void testSetNumOfPlayersWithFalseConditionBecauseOfTooManyPlayers(){

        boolean ans = g.setNumPlayers(10);
        boolean expected = false;

        assertEquals(expected, ans);
    }

    // test setPlayers. Expected false
    @Test
    public void setPlayersTest(){

        boolean ans = g.setPlayers(-3);


        assertEquals(false, ans);
    }

    // test setPlayers. Expected true
    @Test
    public void setPlayersTestWithGivenInput(){

        boolean ans = g.setPlayers(5);


        assertEquals(true, ans);
    }

    /*@Test
    public void testMain(){

        Game.main(new String[] {""});
        assertEquals(0, g.numOfPlayers);
    }*/

    /*@Test
    public void testStartGamePlayerFrames(){
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 5;
        g.addPlayers();
        g.setInitialPos();
        g.boardSize = 7;
        g.setFrames();
        int size = g.playerFrames.size();
        assertEquals(4,size);
    }*/


    // Testing addPlayers by adding players to the array list and checking that the
    // size of the list increased
    @Test
    public void testAddPlayers(){
        g.numOfPlayers = 4;
        g.tm = tm;
        g.addPlayers();
        int size = g.players.size();

        assertEquals(4,size);
    }




    // testing up move
    @Test
    public void testExecuteMoveWithUp(){

        // set up required variables and check the player's new y coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(pos);
        g.executeMove("U",g.players.get(2),3);
        assertEquals(1,g.players.get(2).position.gety());

    }

    // test down move
    @Test
    public void testExecuteMoveWithDownCommand(){

        // set up required variables and check the player's new y coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(pos);
        g.executeMove("D",g.players.get(2),3);
        assertEquals(3,g.players.get(2).position.gety());

    }

    // test startingPosition by checking that the player's starting position x coordinate
    // is equal to the x coordinate generated by the function
    @Test
    public void testStartingPos(){

        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();


        Position spos = g.startingPos();


        Position expectedPos = new Position(spos.getx(),spos.gety());

        assertEquals(expectedPos.getx(), spos.getx());

        // assign nulls to new Position(s) created
        expectedPos = null;
        spos = null;
    }

    // test left move
    @Test
    public void testExecuteMoveWithLeft(){

        // set up required variables and check the player's new x coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(pos);
        g.executeMove("L",g.players.get(2),3);
        assertEquals(1,g.players.get(2).position.getx());

    }

    // test right move
    @Test
    public void testExecuteMoveWithRight(){

        // set up required variables and check the player's new x coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(pos);
        g.executeMove("R",g.players.get(2),3);
        assertEquals(3,g.players.get(2).position.getx());

    }

    //Test set initialPosition
    @Test
    public void testInitialPosition(){

        // set up a new player
        Player player = new Player(5,2);

        // set up tile map
        g.tm = tm;
        g.tm.size = 5;
        g.numOfPlayers = 2;
        g.tm.map = g.tm.setMap();

        // add new player to players array
        g.players.add(player);

        // set the initial position for the player
        g.setInitialPos();

        // check if the starting position is equal to the player's position
        assertEquals(player.startingPosition,player.position);
    }


    // test that revealColour functions correctly with grass tile
    @Test
    public void testGrassRevealColour(){

        // set up a new player
        Player player = new Player(5,2);

        // set up tile map
        g.tm = tm;
        g.tm.size = 5;
        g.numOfPlayers = 2;
        g.tm.map = g.tm.setMap();

        // add new player to players array
        g.players.add(player);

        g.revealColour(0,0,0);

        // set up the expected map
        char[][] expectedPlayerMap = new char[g.tm.size][g.tm.size];
        expectedPlayerMap[0][0] = 'G';
        expectedPlayerMap[0][1] = 'g';
        expectedPlayerMap[0][2] = 'g';
        expectedPlayerMap[0][3] = 'g';
        expectedPlayerMap[0][4] = 'g';

        expectedPlayerMap[1][0] = 'g';
        expectedPlayerMap[1][1] = 'g';
        expectedPlayerMap[1][2] = 'g';
        expectedPlayerMap[1][3] = 'g';
        expectedPlayerMap[1][4] = 'g';

        expectedPlayerMap[2][0] = 'g';
        expectedPlayerMap[2][1] = 'g';
        expectedPlayerMap[2][2] = 'g';
        expectedPlayerMap[2][3] = 'g';
        expectedPlayerMap[2][4] = 'g';

        expectedPlayerMap[3][0] = 'g';
        expectedPlayerMap[3][1] = 'g';
        expectedPlayerMap[3][2] = 'g';
        expectedPlayerMap[3][3] = 'g';
        expectedPlayerMap[3][4] = 'g';

        expectedPlayerMap[4][0] = 'g';
        expectedPlayerMap[4][1] = 'g';
        expectedPlayerMap[4][2] = 'g';
        expectedPlayerMap[4][3] = 'g';
        expectedPlayerMap[4][4] = 'g';

        assertArrayEquals(expectedPlayerMap,player.tm.map);


    }


    // test that revealColour functions correctly with water tile
    @Test
    public void testWaterRevealColour(){

        // set up a new player
        Player player = new Player(5,2);

        // set up tile map
        g.tm = tm;
        g.tm.size = 5;
        g.numOfPlayers = 2;
        g.tm.map = g.tm.setMap();

        // add new player to players array
        g.players.add(player);

        g.revealColour(1,4,0);

        // set up the expected map
        char[][] expectedPlayerMap = new char[g.tm.size][g.tm.size];
        expectedPlayerMap[0][0] = 'g';
        expectedPlayerMap[0][1] = 'g';
        expectedPlayerMap[0][2] = 'g';
        expectedPlayerMap[0][3] = 'g';
        expectedPlayerMap[0][4] = 'g';

        expectedPlayerMap[1][0] = 'g';
        expectedPlayerMap[1][1] = 'g';
        expectedPlayerMap[1][2] = 'g';
        expectedPlayerMap[1][3] = 'g';
        expectedPlayerMap[1][4] = 'g';

        expectedPlayerMap[2][0] = 'g';
        expectedPlayerMap[2][1] = 'g';
        expectedPlayerMap[2][2] = 'g';
        expectedPlayerMap[2][3] = 'g';
        expectedPlayerMap[2][4] = 'g';

        expectedPlayerMap[3][0] = 'g';
        expectedPlayerMap[3][1] = 'g';
        expectedPlayerMap[3][2] = 'g';
        expectedPlayerMap[3][3] = 'g';
        expectedPlayerMap[3][4] = 'g';

        expectedPlayerMap[4][0] = 'g';
        expectedPlayerMap[4][1] = 'w';
        expectedPlayerMap[4][2] = 'g';
        expectedPlayerMap[4][3] = 'g';
        expectedPlayerMap[4][4] = 'g';

        assertArrayEquals(expectedPlayerMap,player.tm.map);


    }


    // Test up move with out of bounds
    @Test
    public void testUpWithOutOfBounds(){

        // set up required variables and check the player's new y coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(new Position(0,0));
        g.executeMove("U",g.players.get(2),3);
        assertEquals(0,g.players.get(2).position.gety());
    }

    // Test down move with out of bounds
    @Test
    public void testDownWithOutOfBounds(){

        // set up required variables and check the player's new y coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(new Position(6,6));
        g.executeMove("D",g.players.get(2),3);
        assertEquals(6,g.players.get(2).position.gety());
    }

    // Test left move with out of bounds
    @Test
    public void testLeftWithOutOfBounds(){

        // set up required variables and check the player's new y coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(new Position(0,0));
        g.executeMove("L",g.players.get(2),3);
        assertEquals(0,g.players.get(2).position.getx());
    }

    // Test right move with out of bounds
    @Test
    public void testRightWithOutOfBounds(){

        // set up required variables and check the player's new y coordinate
        g.numOfPlayers = 4;
        g.tm = tm;
        g.tm.size = 7;
        g.tm.map = g.tm.setMap();
        g.addPlayers();
        g.players.get(2).setPosition(new Position(6,6));
        g.executeMove("R",g.players.get(2),3);
        assertEquals(6,g.players.get(2).position.getx());
    }



    // set the objects to null
    @After
    public void teardown(){
        g = null;
        tm = null;
        pos = null;
        treasurePos = null;
    }
}
